src-vue/src/plugins/store.ts, src-vue/src/views/DeveloperView.vue
Right now it's a single toggle button. In the future it should be a dropdown menu
=> Allow switching between release channels

src-vue/src/views/DeveloperView.vue
In the future, this button should be moved to a "Repair" view. For now I'm putting it into Dev view for testing.
=> feat: Initial logic to disable all but core mods

src-vue/src/App.vue
=> fix: App bar drag

scripts/create-release-file.py
Modifies script that crease release file to show link in Tauri app update prompt.
=> chore: Link release notes in update notification

.gitignore
Files no longer exist since the UI rewrite
=> chore: Remove old entries from gitignore

.github/workflows/push-test.yml, .github/workflows/release.yml
We've been running on 20.04 for too long, time to change it :>
=> chore: Update Ubuntu version in CI

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-vue/src/App.vue, src-vue/src/main.ts, src-vue/src/utils/Tabs.ts, src-vue/src/views/DeveloperView.vue, src-vue/src/views/ModsView.vue
=> feat: Add initial skeleton for ModsView

src-vue/package-lock.json, src-vue/package.json
Volar was complaining that the `vue-tsc` dependency was out of date so I bumped it to 1.0 or higher ^^
=> chore: Update `vue-tsc`

src-vue/src/views/ModsView.vue
=> feat: Enable toggling enabled mods 

src-tauri/src/lib.rs, src-tauri/src/main.rs
=> refactor: Rename function to better fit behaviour

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/repair_and_verify/mod.rs
Only a single function for now as a sort of proof-of-concept.
=> refactor: Move functions to dedicated file

.editorconfig, README.md
Describes some basic formatting like indentation with spaces, indentation size, final newlines, etc.
=> style: Add `.editorconfig` file

src-vue/src/views/DeveloperView.vue
Makes buttons a bit more organised ^^
=> feat: Add categories for dev mode buttons

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/mod_management/mod.rs
Some mods have comments in their JSON. Northstar handles it fine, so we should too.
More info on JSON5: https://json5.org/
=> feat: Add JSON5 support, allows comments in JSON

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/lib.rs, src-tauri/src/main.rs
Had to update some code with version bump.
=> chore: Bump libthermite version to 0.3.3

src-tauri/src/github/release_notes.rs, src-tauri/src/lib.rs, src-tauri/src/main.rs
One more step towards reducing code re-use ^^
=> refactor: Move GitHub API fetch to submodule and re-use existing function

src-vue/src/views/ModsView.vue
=> feat: Add element-plus scrollbar to mods view

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs
Moving a single function initially for PoC and to keep changes small.
=> refactor: Start moving NS related logic to own module

src-vue/src/plugins/store.ts, src-vue/src/views/DeveloperView.vue
WIP commit still the whole logic is a bit clunky, might wanna refactor
=> feat: Store game path in persistent store

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/repair_and_verify/mod.rs
Getting log files is part of repair and troubleshooting and should therefore be in the appropriate module.
=> refactor: Move function to dedicated module

README.md, scripts/create-release-file.py, src-tauri/src/github/release_notes.rs, src-tauri/tauri.conf.json
Update all references of personal repo and change them to R2NorthstarTools org.
=> chore: Update all references of personal repo

src-vue/src/main.ts
ThunderstoreView was further below.
=> style: Group View import lines together

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-vue/src/plugins/store.ts, src-vue/src/views/DeveloperView.vue
Hidden behind dev view. Helps with testing as dev builds of Northstar do not update patch number so an update check bypassing button is necessary to launch dev builds of Northstar.
=> feat: Option to launch NS bypassing update check

docs/DEVELOPMENT.md
Introduces languages and tools used in FlightCore
=> docs: Introduce languages used in FlightCore

docs/DEVELOPMENT.md
To help with on-boarding new contributors.
=> docs: Link Tauri intro and tutorial

src-tauri/src/github/release_notes.rs, src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/platform_specific/linux.rs, src-tauri/src/platform_specific/mod.rs, src-tauri/src/platform_specific/windows.rs, src-tauri/src/repair_and_verify/mod.rs
Just manually ran the auto-format over all the Rust code ^^
=> style: Auto-format all Rust code

src-vue/src/views/DeveloperView.vue
As suggested by @ASpoonPlaysGames
Rendered:
=> feat: Give example for modstring in text box

docs/DEVELOPMENT.md
- Mention how to call backend from frontend
- Mention [Element Plus](https://element-plus.org/) component library
=> docs: Improve developer documentation

docs/DEVELOPMENT.md
Just mention some way how to ask for help when trying to contribute.
=> docs: Mention ways of reaching out

src-vue/src/style.css, src-vue/src/views/ChangelogView.vue, src-vue/src/views/DeveloperView.vue, src-vue/src/views/ModsView.vue, src-vue/src/views/SettingsView.vue, src-vue/src/views/ThunderstoreModsView.vue
I hope title is self-explanatory :)
I took advantage of this to remove some duplication in CSS styles.
Closes #65.
=> feat: Add scrollbar to all views

README.md
Forgot to link to FAQ when I made it ^^"
=> docs: Link to FAQ from README

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/github/release_notes.rs
This way we don't spam the end-user with an update notification before an update is fully built and released.
=> feat: Threshold before showing update notification

src-tauri/src/main.rs, src-vue/src/App.vue, src-vue/src/components/PlayButton.vue, src-vue/src/plugins/store.ts, src-vue/src/style.css, src-vue/src/utils/thunderstore/ThunderstoreMod.d.ts
- [fix: increase background scale to hide white border on Windows](https://github.com/R2NorthstarTools/FlightCore/commit/5c3cbe435a1e301cbedf03dd36361366bb2d48a7)
- [fix: prevent channel switching while game is running](https://github.com/R2NorthstarTools/FlightCore/commit/edf9c8e861b710f5f3c97f0141a166758d5dc87e)
- [fix: blur all views except main one](https://github.com/R2NorthstarTools/FlightCore/commit/458bae18899cd116fa229924d31505fc26b04ff8)
- [fix: do not display deprecated mods in thunderstore view](https://github.com/R2NorthstarTools/FlightCore/commit/6fea46b5f848d29f359d5959e184f5a0204bb000)
- [refactor: remove useless debug print](https://github.com/R2NorthstarTools/FlightCore/commit/49598004d148d3b4cb8b3232a94235042a8713f2)
- [build: disable context menu in release …
=> Small fixes

src-vue/src/views/DeveloperView.vue
=> feat: Show warning banner on DevView

src-tauri/src/github/release_notes.rs, src-tauri/src/main.rs, src-vue/src/plugins/store.ts, src-vue/src/utils/FlightCoreVersion.d.ts
Show version number of new release in outdated warning.
=> feat: Show newest version number

src-vue/src/plugins/store.ts
=> style: Formatting fixes in TypeScript code

src-vue/src/views/DeveloperView.vue
Typo and referencing wrong functionality.
=> fix: Fix wrong comments

src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/repair_and_verify/mod.rs
Autoformatted all Rust source code that wasn't formatted properly.
Maybe we should start enforcing formatting via CI? ^^
=> chore: Autoformat Rust source files

src-vue/src/App.vue
=> fix: Set current route as menu active item

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs
And fix corresponding code that broke in the process
Basically just removing `await`s as the networking functions are no longer async.
=> chore: Bump libthermite version to 0.5.2

.github/workflows/push-test.yml, .github/workflows/release.yml
Replaces all actions of [`actions-rs`](https://github.com/actions-rs) with ones by other authors that are actually maintained.
TODO:
When done, nearly closes #189
=> build: Replace unmaintained action

.github/workflows/push-test.yml, .github/workflows/release.yml
Updates `actions/checkout@v2` to `actions/checkout@v3`
Closes #189
=> build: Update outdated checkout action

src-tauri/src/lib.rs
Use the variable name directly inside the string.
=> fix: Address clippy warnings regarding format!()

src-tauri/src/lib.rs
=> fix: Remove unnecessary borrows

src-tauri/src/lib.rs
`clippy` said this is way is better...
=> fix: Adjust code for single iteration loop

LICENSE
Simple MIT license
Closes #234
=> chore: Add License

src-tauri/src/mod_management/mod.rs, src-tauri/src/repair_and_verify/mod.rs
=> fix: Replace `<=0` with `.is_empty()`

docs/DEVELOPMENT.md
=> docs: Expand on the Setup (build) instructions

docs/DEVELOPMENT.md
Add explanation on how to add a new language to the language selector component
=> docs: Explanation on expanding language selector

src-tauri/src/github/mod.rs, src-tauri/src/lib.rs, src-tauri/src/repair_and_verify/mod.rs
Various fixes based on `clippy` output.
With this PR we are down to 3 more warnings, 2 of which will require me to also change something in front-end, 1 I will need some assistance to resolve.
=> fix: Another set of various clippy fixes

src-vue/src/components/PullRequestsSelector.vue
Adds filter inputs in PR selector to filter launcher/mods pull requests.
Closes #204.
---
=> feat: Filter PRs

src-tauri/src/github/mod.rs, src-tauri/src/github/pull_requests.rs, src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/northstar/mod.rs, src-tauri/src/repair_and_verify/mod.rs
there are probably more places where pass by reference can be used
=> Use pass by reference where possible

src-tauri/src/mod_management/mod.rs
that's it
kinda need this for #267
=> refactor: Use error in `ParsedThunderstoreModString::FromStr` instead of panic

src-tauri/src/github/pull_requests.rs
Previously we only fetched the first page which caused us to miss older pull requests.
Closes #297
=> fix: Fetch multiple pages from GitHub PR api

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml
https://tauri.app/blog/2023/05/03/tauri-1-3/
Closes #278
=> chore: Update Tauri to 1.3

src-tauri/src/mod_management/mod.rs
related to https://github.com/R2NorthstarTools/FlightCore/pull/267#discussion_r1186120176
to delete the folder instead of files, the function would need a rewrite since the implementation rn doesn't allow it
=> refactor: Always remove zip files

src-tauri/src/lib.rs, src-tauri/src/main.rs
This PR aims to refactor Northstar installation code to make it easier to later add functionality to install a specific Northstar versions
=> refactor: Prepare code for installing older Northstar versions

src-tauri/Cargo.lock
=> chore: Bump steamlocate to 1.2.1

src-vue/src/components/LanguageSelector.vue, src-vue/src/main.ts
Adds _Polish_ into the language dropdown menu in settings.
=> feat: Enable Polish translations

src-vue/src/i18n/lang/pl.json
Translations update from [Weblate](https://translate.harmony.tf) for [Northstar/FlightCore](https://translate.harmony.tf/projects/northstar/flightcore/).
Current translation status:
=> i18n: Translations update from Weblate

src-vue/src/components/LanguageSelector.vue, src-vue/src/main.ts
Adds _Russian_ into the language dropdown menu in settings.
=> i18n: Enable Russian translations

src-tauri/src/lib.rs, src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs
=> refactor: Move `launch_northstar` to own module

src-tauri/src/main.rs, src-tauri/src/northstar/install.rs, src-tauri/src/util.rs
=> refactor: Move `extract` function to util submod

src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs, src-tauri/src/util.rs
=> refactor: Move Origin/NS running check to util mod

src-tauri/src/github/release_notes.rs, src-tauri/src/main.rs, src-tauri/src/northstar/install.rs, src-tauri/src/northstar/mod.rs, src-vue/src/plugins/store.ts
Removes the `*_caller` pattern for all functions where it's unnecessary.
=> refactor: Remove caller pattern

src-vue/src/views/mods/LocalModsView.vue
Forgot about that one in #342, whoops (/.-)
=> fix: Add missing fuzzy filter for local mods search

src-tauri/src/main.rs
Basically just some syntax related code refactoring.
=> refactor: Use fully qualified path syntax in `main.rs`

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/mod_management/mod.rs, src-tauri/src/northstar/install.rs
I had to address an issue in thermite itself to get it to build, but installing Northstar and mods seems to work fine now
=> wip: basic working changes

src-tauri/src/main.rs
relying on a file to be parsed in time is unreliably, and if the file is open while we delete it we may run into locking problems downside is that this gives a fugly prompt
=> fix: Pass launch options to Steam

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml
Bump Tauri to newest stable release.
=> chore: Bump Tauri to 1.4

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/northstar/install.rs
=> feat: Add warning for Snap installations

src-tauri/Cargo.toml, src-tauri/src/main.rs
With Tauri 2.0 this will require a plugin
=> feat: Replace MessageBoxW invocation with Tauri dialog

src-tauri/Cargo.lock
Haven't bumped Rust dependencies in a while so this is gonna be fun :>
=> chore: Bump Rust dependencies

src-vue/src/components/LocalModCard.vue, src-vue/src/components/ThunderstoreModCard.vue, src-vue/src/plugins/modules/pull_requests.ts, src-vue/src/plugins/store.ts, src-vue/src/views/DeveloperView.vue, src-vue/src/views/RepairView.vue, src-vue/src/views/SettingsView.vue
=> chore: Store `game_path` and `install_type` as `GameInstall` in store

src-vue/src/plugins/store.ts
Just fixes a small typo. It's close to an area that #445 touches so I'm gonna merge the other first as I don't know whether the closeness can also cause merge conflict
=> chore: Fix typo in comment

src-tauri/src/main.rs, src-tauri/src/mod_management/legacy.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/northstar/install.rs, src-tauri/src/northstar/mod.rs, src-tauri/src/repair_and_verify/mod.rs, src-vue/src/plugins/store.ts, src-vue/src/utils/GameInstall.ts
adds a profile attribute to GameInstall.
Should not change any frontend behavior.
=> refactor: Add Profile to GameInstall

src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs, src-vue/src/plugins/store.ts
=> refactor: Replace naive `game_path` argument with `GameInstall`

src-tauri/src/main.rs, src-tauri/src/northstar/install.rs, src-vue/src/plugins/store.ts, src-vue/src/views/DeveloperView.vue, src-vue/src/views/RepairView.vue
relevant for #444, since we need to know what Northstar Profile to update.
=> refactor: Migrate install related functions to `GameInstall`

src-tauri/src/development/mod.rs, src-tauri/src/github/pull_requests.rs, src-tauri/src/mod_management/mod.rs, src-tauri/src/northstar/install.rs, src-tauri/src/repair_and_verify/mod.rs
temp folder could probably be reused for a lot more things, like extracting Northstar before moving files into the correct place.
=> refactor Generalise temporary directory structure

src-vue/package-lock.json
Bumping npm dependencies to get everything up to date again ^^
Also in part in preparation for #358
=> chore: Bump npm dependencies

src-vue/src/i18n/lang/de.json, src-vue/src/i18n/lang/en.json, src-vue/src/views/DeveloperView.vue, src-vue/src/views/RepairView.vue
Helped someone in tickets so I'm moving it from DevView to RepairView.
Translations are only in English and German, gonna leave the rest to Weblate
=> feat: Move button for killing NS to RepairView

src-vue/src/i18n/lang/en.json, src-vue/src/views/ChangelogView.vue, src-vue/src/views/SettingsView.vue
this will later be used to manage northstar profiles.
=> feat: Add dialog box with a table of all profiles

src-vue/src/components/LanguageSelector.vue, src-vue/src/main.ts
Danish translations are complete with #506 so they can be enabled now ^^
=> i18n: Enable Danish translations

docs/TROUBLESHOOTING.md
Documenting a fatal Linux issue I ran into trying to run this program.
See #571 for context.
Closes #571
=> docs: Mention workaround for blank window on Linux

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml
Combines:
- #596 
- #598 
- #601 
- #602 
into a single PR as all the libraries are more or less dependent on each other.
=> chore: Bump tauri version

src-vue/src/style.css
Makes popup dialog windows slightly larger and prevents words from breaking.
Closes #608.
=> fix: Update popup style

src-tauri/src/main.rs, src-tauri/src/platform_specific/linux.rs, src-tauri/src/platform_specific/mod.rs
Move platform specific logic to appropriate module in an effort to clean up `main.rs`
=> refactor: Move platform specific logic to proper mod

src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs, src-tauri/src/platform_specific/mod.rs
In an effort to clean up `main.rs`
=> refactor: Move `get_host_os` to module

src-tauri/Cargo.lock, src-tauri/Cargo.toml
=> chore: Properly populate package manifest info

src-tauri/src/main.rs
Simply adds some doc comments to some struct explaining what they are used for.
=> docs: Add doc comments to some structs

src-tauri/src/github/pull_requests.rs, src-tauri/src/main.rs, src-tauri/src/platform_specific/windows.rs, src-tauri/src/repair_and_verify/mod.rs
Moves functions related to game install path verification checks to dedicated module in an effort to clean up `main.rs`
=> refactor: Move repair/verify related funcs to mod

src-tauri/src/main.rs, src-tauri/src/util.rs
In order to further clean up `main.rs`.
=> refactor: Move relevant functions to util module

src-tauri/src/main.rs, src-tauri/src/northstar/mod.rs
In order to further clean up `main.rs`.
=> refactor: Move relevant functions to northstar module

src-tauri/src/main.rs, src-tauri/src/mod_management/mod.rs
Move `install_mod_wrapper` to `mod_management` module to clean up `main.rs`.
=> refactor: Move `install_mod_wrapper`

package-lock.json, package.json, src-tauri/Cargo.lock
Supersedes
- #713
- #714
- #715
- #716
By combining them all in a single PR
=> chore: Bump Tauri dependencies

src-tauri/src/northstar/mod.rs
`bypass_checks` was never used for `launch_northstar_steam`
=> refactor: Remove unused function arg

src-vue/src/views/DeveloperView.vue
=> style: Trim trailing whitespace

src-tauri/src/main.rs
Remove unused struct and address clippy issue in the process.
=> fix: Remove unused struct

src-tauri/src/platform_specific/linux.rs
Download is broken, please complain to Emerald about it
=> fix: Change Proton detection for new GE base

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/northstar/install.rs, src-tauri/src/northstar/mod.rs, src-tauri/src/platform_specific/linux.rs
Lets us get rid of `steamy_vdf` and other out of date dependencies
hooray
please merge thank you <3
=> chore: bump steamlocate from 1.2 to 2.0.0-beta.2

src-vue/src/i18n/lang/en.json
Translation for showing NSFW mod was missing from #964
=> fix: Add missing translation

.github/dependabot.yml
So that there's a bit less PR spam from dependabot
=> chore: Change dependabot PR interval to monthly

.github/workflows/push-test.yml, .github/workflows/release.yml, src-vue/tsconfig.json
Bumps Node version to 18 as 16 is EOL.
=> chore: Bump node version to 18

src-tauri/src/constants.rs
Updates Vanilla+'s name check to include the new name. Still kept the old one just in case
=> Update Vanilla+ name check

src-vue/src/App.vue
=> fix: Colour header bar to keep text legible
