src-vue/src/plugins/store.ts

Allows skipping clicking version number 5 times when working on FlightCore.
Release builds are not in debug mode, so dev mode is still disabled by default for end-users.

feat: Enable dev mode directly if in debug mode

---

.github/workflows/push-test.yml

Remedies the issue that anyone pushing without access to private key will see their CI fail.

fix: Disable self-updater in CI builds from push

---

src-vue/src/plugins/store.ts
src-vue/src/views/SettingsView.vue

Adds a new field to state that stores FlightCore version number. Version number is pulled from backend on application launch.

feat: Show own version number in settings view

---

README.md
src-vue/package-lock.json
src-vue/package.json
src-vue/src/plugins/store.ts
src-vue/src/views/DeveloperView.vue

Adds persistent store using [`tauri-plugin-store`](https://github.com/tauri-apps/tauri-plugin-store).
For now, it's only used to store the selected release canal.

feat: Add persistent store

---

src-tauri/src/lib.rs
src-tauri/src/main.rs
src-vue/src/views/DeveloperView.vue

Allows for comprehensive error messages depending on which check failed (we only have one check right now but that will change in the future).

refactor: Use `Result<>` return type for Linux checks

---

src-tauri/src/lib.rs

This is more of a hotfix, we should really just use propery regex or something better instead.

fix: Strip leading zeroes from rc version number

---

src-vue/src/App.vue
src-vue/src/style.css
src-vue/src/utils/NorthstarMod.d.ts
src-vue/src/views/ModsView.vue

Simply parses `enabledmods.json`. In the future we should also opt to check individual mods and compare with the JSON file.
This is #17 but with only the essential CSS changes to make the mod list properly scrollable.

feat: Show installed mods

---

src-tauri/src/lib.rs

Instead of re-implementing existing logic just re-use what we already have.

refactor: Use existing function for enabled mods

---

src-tauri/src/main.rs

This way none of them are run on main thread and as such if a function panics, it will only crash that specific thread allowing the rest of the application to survive.
The only exception is `force_panic()` as its purpose is hard crashing the application.
From the frontend side of things, `invoke()` is already async, so no frontend changes are needed.

refactor: Make all functions async

---

src-tauri/src/lib.rs
src-tauri/src/main.rs

All that is returned as the error type is a string so there's no point in using a custom error type when we can just have the error type be a string.

refactor: Return error string instead of `anyhow!()`

---

src-tauri/src/lib.rs
src-tauri/src/main.rs

Set the function to async but it was still using blocking version of `reqwest`.
Resolves https://github.com/GeckoEidechse/FlightCore/pull/35#issuecomment-1300952751

fix: Resolve thread crash due to block in async

---

.github/workflows/push-test.yml
.github/workflows/release.yml

Version 2 uses Node 12 which is being deprecated by GitHub. Version 3 should use Node 16 instead.

chore: Bump checkout action version

---

src-vue/src/views/PlayView.vue
src-vue/src/views/SettingsView.vue

Clicking FC version activates dev instead of clicking Northstar version.
Makes dev mode a bit more "hidden" (i.e. less likely to be accidentally opened by end-user) and it's more logical to click FlightCore version to open **FlightCore** dev mode as opposed to clicking Northstar version.

refactor: Clicking FC version activates dev

---

src-tauri/src/main.rs
src-vue/src/plugins/store.ts

Return `Result<String, String>` for getting Northstar version as opposed to using an empty string to indicate an error.

refactor: Return Result<> for getting NS version

---

src-tauri/src/github/release_notes.rs

So that it can be re-used by other functions later such as for checking newest FlightCore version by checking against GitHub releases.

refactor: Splice out GH release API fetch function

---

src-vue/src/App.vue
src-vue/src/plugins/store.ts

Helps with differentiating which window is which when both developing FlightCore and is using release version at the same time.
Wouldn't be the first time I accidentally nearly confused the two :P
Rendered result:

feat: Show stripped title bar on debug build

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

Worked fine on my end. Resolves panic when trying to install `cat_or_not-mp_mirror_city-0.1.0` by throwing a catch-able error instead.

chore: Bump libthermite version to 0.3.4

---

src-tauri/src/lib.rs
src-tauri/src/mod_management/mod.rs
src-vue/src/utils/NorthstarMod.d.ts

This updates the returned NorthstarMod struct/object to also contain the related Thunderstore mod that a Northstar mod may belong to.

feat: Return Thunderstore mod string of installed mods.

---

.github/workflows/push-test.yml
.github/workflows/release.yml

`v1` uses Node 12 which is being deprecated on GitHub actions.

chore: Bump actions/setup-node to v3

---

src-vue/src/plugins/store.ts

Setting install path manually when one exists already will error out on trying to delete the non-existing "no install found" notification using its non-existing handle.

fix: Catch error for missing handle

---

README.md

With Viper 1.6.3, stack traces are not shown by default, instead a simple "Unknown Error!" toast is shown, where a user can choose to click it, to then see the stack.
Whether the text should be completely removed or not, is of course, not up to me, I just thought it would be an idea to at the very least, rephrase it, now that stack traces aren't shown by default.

edit: remove text about Viper showing stack trace

---

src-tauri/src/northstar/mod.rs
src-tauri/src/repair_and_verify/mod.rs

This way we only define them in one place which makes adding/removing core mods (e.g. `Northstar.Coop`) easier in the future.

refactor: Define core mods in global const

---

package-lock.json
package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml

Update Tauri dependencies to `1.2`
Also requires bumping Rust to `1.62`

chore: Update Tauri depedencies to 1.2

---

src-tauri/src/mod_management/mod.rs

When toggling a mod on enabled mods that is not present in `enabledmods.json` we would previously just error out. Now we rebuild the `enabledmods.json` file in a Northstar compatible format and then toggle the mod in question.
This means no more
:D
Also, nice PR number :3

feat: Rebuild `enabledmods.json` if value not found

---

docs/DEVELOPMENT.md

- Remove obsolete section mentioning how to compile Typescript code (no longer applies)
- Add note about auto-recompile
- Attempt to improve setup instructions

docs: General cleanup

---

docs/DEVELOPMENT.md

As a hint for new contributors. I have little hope of everyone actually following but that's what we have squash merging for :P

docs: Mention semantic commit messages

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/platform_specific/windows.rs

Now using a library instead of calling a PowerShell command should prevent the PowerShell window from opening.

fix: Stop opening PS to get Origin game path

---

src-tauri/Cargo.toml

Should resolve https://github.com/R2NorthstarTools/FlightCore/pull/85#issuecomment-1336846037
Technically `1.64` would be enough to solve that issue but[ `1.65` adds let-else statements to stable which allow for more compact and readable code in some cases](https://www.youtube.com/watch?v=U-5_bumwH9w). ^^

chore: Bump Rust version to 1.65

---

src-vue/package-lock.json

The vscode Vue Language Features extension (Volar) was complaining that the Vue dependency is out of date. Decided to just bump all of them in the process :P

chore: Bump Node dependencies

---

src-tauri/Cargo.lock

If we're already in the process of bumping dependencies, why not these as well ¯\_(ツ)_/¯

chore: Bump Rust dependencies

---

src-tauri/src/repair_and_verify/mod.rs

For this we first rebuild the `enabledmods.json` file. This ensures that all installed mods are actually listed there.
The function was originally created before we could rebuild `enabledmods.json` by checking installed mods.

fix: Make sure all non-core mods get disabled

---

src-tauri/src/lib.rs
src-tauri/src/mod_management/mod.rs
src-vue/src/utils/NorthstarMod.d.ts

This allows other functions to get a mod directory directly which is useful for e.g. deleting a mod.

feat: Expose installed NS mod directory

---

src-tauri/src/lib.rs

Simply run cmd with `start "" "PATH/TO/NORTHSTAR_EXE"`

feat: Start Northstar properly detached

---

src-vue/src/plugins/store.ts
src-vue/src/views/ModsView.vue

Display a message on empty mods view instead of showing an error notification.
Closes #64.

fix: Mod view with no game install

---

.github/workflows/push-test.yml
.github/workflows/release.yml
src-tauri/src/main.rs

To reduce CI runtime by making use of cached artifacts

build: Cache Rust build artifacts

---

src-vue/src/App.vue
src-vue/src/plugins/store.ts
src-vue/src/style.css
src-vue/src/views/PlayView.vue

This adds a new window control that enables user to maximize/minimize window.
It also restructures the menu bar, to properly display menu items when menu bar width reduces.
---

feat: Maximize button + clean menubar layout

---

src-tauri/src/github/release_notes.rs

Instead of deserializing into a generic serde struct and then extracting specific value from it, deserialize directly into the struct we want.
Basically less lines of code thanks to serde :sparkles: magic :sparkles:

refactor: Deserialize into struct directly

---

src-vue/src/plugins/store.ts
src-vue/src/views/SettingsView.vue
src-vue/src/views/ThunderstoreModsView.vue

This introduces pagination for Thunderstore mods, not displaying all of them at once to improve performances.
Pagination is sensible to mods filtering.

feat: Thunderstore mods pagination

---

src-tauri/src/main.rs
src-tauri/src/mod_management/mod.rs
src-tauri/src/repair_and_verify/mod.rs
src-vue/src/plugins/store.ts
src-vue/src/views/DeveloperView.vue
src-vue/src/views/ModsView.vue

Removes the unnecessary `function_caller` pattern by just adding the `#[tauri::command]` macro to the corresponding function directly.
I couldn't remove the pattern for all functions cause some seem to throw weird compiler macro errors when I do. Needs further investigating but the adjusted functions in this PR all work fine ^^

refactor: Remove unnecessary caller function pattern

---

src-tauri/src/constants.rs
src-tauri/src/github/release_notes.rs
src-tauri/src/lib.rs

Moved user agent there for now.
Storing all global consts in a single file makes adjusting them easier as one also have to look at a single place. This is especially useful for anyone wanting to make their own spin/fork of the application (NorthstarCN _\*hint\*_ _\*hint\*_ ;P)

refactor: Store global const in separate file

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/lib.rs
src-tauri/src/mod_management/mod.rs

This updates to version `0.4.0` of [`libthermite`](https://crates.io/crates/libthermite).
In the process, we now also no longer write the Thunderstore mod string to the Northstar mod's `mod.json` but rather copy the `manifest.json` from the Thunderstore mod into the Northstar mod and add a file called `thunderstore_author.txt` that contains the author name of the Thunderstore mod to uniquely map a Northstar mod to a Thunderstore mod.
This is done to increase compatibility with Viper and VTOL. See also the discussion here: https://github.com/0neGal/viper/issues/165
Reading `mod.json` for Thunderstore string is still supported for the time being. In the future it will be changed to a "converter" and then later will be fully deprecated.

refactor: Bump libthermite

---

src-tauri/src/mod_management/mod.rs

Instead of doing a simply string replace, we now parse the mod string into an object.

fix: Properly parse mod string

---

src-tauri/src/main.rs

Seems like I forgot to remove it when I did some code refactoring. Removes a compiler warning about unused imports.

fix: Remove unused serde import in `main.rs`

---

.github/workflows/push-test.yml
src-tauri/build.rs

Performs source code formatting check in CI and fails if the formatting is wrong.
TODO:
Closes #144

feat: Add Rust code format check to CI

---

src-tauri/src/lib.rs

Single line change. No need for custom error type if we just return a string anyway.

refactor: Remove unnecessary use of anyhow

---

README.md
docs/index.html

This PR introduces the `docs/index.html` file which when loaded will take in varies queries then redirect you to the latest release page or files, without having to update the version numbers every release, as it fetches the latest automatically.
When deployed you should be able to go to the following links, and the various files should just download, the last one will however redirect you to the latest release page instead, as a fallback. I also took the liberty of changing the README's download link to match.
[r2northstartools.github.io/FlightCore/index.html?win-setup](https://r2northstartools.github.io/FlightCore/index.html?win-setup)<br> ---> FlightCore_<version>_x64_en-US.msi
[r2northstartools.github.io/FlightCore/index.html?win-zip](https://r2northstartools.github.io/FlightCore/index …

docs: Redirector to up-to-date releases

---

src-tauri/src/repair_and_verify/mod.rs

refactor: Deal with `fs::read_dir` failure instead of checking if exists

---

src-tauri/src/mod_management/mod.rs

`parse_installed_mods` will panic if Northstart mods folder doesn't exist so we check for that before trying to read from it.

fix: Prevent mods view from crashing if Northstar is not installed

---

src-tauri/src/mod_management/mod.rs

This gets rid of a bunch of code by making use of [`serde`](https://crates.io/crates/serde) functionality. This should have honestly been written like this in the first place but when I first used `serde` I wasn't aware of that functionality even though it's its defining feature ^^"

refactor: Parse using serde deserialisation

---

src-vue/src/views/mods/LocalModsView.vue

Dead simple 1-line addition, that makes it a bit clearer what the icon signifies ^^
**Rendered:**
screenshot tool did not capture my mouse cursor >:(

feat: Show text when hovering Thunderstore icon

---

src-tauri/tauri.conf.json

Seems like +10px on the horizontal was enough ^^
Before:
vs with this PR:
Supersedes #165 somewhat

fix: Slightly increase window size to better fit list of mods in Thunderstore mod browser

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/constants.rs

Uses a crate that allows for formatting at compile time.
User agent is `FlightCore/MAJOR.MINOR.PATCH`, e.g. currently `FlightCore/1.7.0`.
Among other things, this allows for seeing percentage of different versions deployed on masterserver when FlightCore performs query to `/client/servers`.
Closes #170

feat: Add version number to user-agent

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

Current one is `0.27.0` and Sentry dashboard is complaining that it's outdated... ^^

chore: Bump sentry crate to 0.29.2

---

src-tauri/src/main.rs

Enable attaching stacktrace to see the function in which the crash happened.
https://docs.sentry.io/platforms/rust/configuration/options/#attach-stacktrace

feat: Better stacktrace in Sentry dashboard

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

Instead of a branch specify specific commit.
This is done to later run `cargo update`. Currently running said command updates the dependency to a broken build.
Fixing `tauri-plugin-store` to a specific working commit allows for running `cargo update` again.
Note that this is the same commit as the one specified in the `Cargo.lock` and incidentally also the last working commit of that crate ^^"

fix: Specify commit for tauri-plugin-store

---

src-tauri/src/lib.rs
src-tauri/src/main.rs
src-tauri/src/platform_specific/mod.rs

Makes sure that Windows/Linux specific functions are only compiled on their respective OS.
Will also help with reducing diff of #180

refactor: Properly set cfg macro for OS conditional compilation

---

.vscode/extensions.json

Adds `vue.Volar` to list of recommended vscode extensions. This should have been there already from the get-go tbh ^^

build: Add Volar to recommended vscode extensions

---

.github/workflows/push-test.yml

Splits up the Windows and Linux artifacts into separate zip folders.
This is especially useful for testing Windows builds as the Linux ones are huge due to being an AppImage. Windows is tiny (7MB) in comparison and as such this means when testing CI build on Windows with this PR one goes from downloading 300MB (Windows + Linux files) to just 7MB (only Windows files).

build: Separate zips for artifacts for Windows and Linux

---

.github/workflows/push-test.yml
.github/workflows/release.yml

Upload Windows debug symbols which are stored in `.pdb` file to artifacts.
This is done as part of an attempt to solve #166

Upload Windows `.pdb`

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

Update `sentry` backend dependency to newest release. Solved #166 as on the newer release `debug_images` are uploaded by default.
Note that this raises the min Rust version required to `1.66`. If that's an issue we could also use `0.29.3` of `sentry` but I don't really see a point to purposefully stay on older release ^^

chore: Bump sentry to 0.30.0

---

package-lock.json
package.json
src-tauri/Cargo.lock
src-vue/package-lock.json

Bumps all dependencies. Most notably updates Tauri to `v1.2.3` from `v1.2.1`

chore: Bump all dependencies

---

.github/workflows/push-test.yml

v2 used an outdated version of Node JS and GitHub warns about deprecation. As such we should bump to newer release.
Part of solving
- #189

chore: Bump checkout action to v3

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

This adds a change needed for making progressbar work on Northstar/mod download.

chore: Bump libthermite to 0.5.3

---

.github/workflows/release.yml

Previously, I would have to manually upload `.pdb`s to Sentry manually myself after every release. Obviously doing things manually is stupid so this adds some CI steps to upload the Windows debug symbols to sentry.io via CI.
(top one is the newest uploaded in a test run)
For successful test run see https://github.com/GeckoEidechse/Temp-FlightCore/actions/runs/4356663525/jobs/7614981650#step:11:16
(this took way to many attempts, the failed step in CI after is expected cause the repo is a fork with some changes for faster testing)

build: Upload Windows pdb to Sentry via CI

---

src-vue/src/views/DeveloperView.vue
src-vue/src/views/RepairView.vue

Moves buttons previously located to the new repair window that was added in #129

refactor: Move buttons to repair window

---

src-vue/src/views/DeveloperView.vue
src-vue/src/views/SettingsView.vue

Moving the button from DeveloperView to Settings means that it's now accessible to the end-user, essentially "releasing" that feature ^^

feat: Move open repair window button to settings

---

src-tauri/src/lib.rs

This will show up in sentry dashboard on crash and will help me solve a thread crash that's caused by Northstar failing to get installed.

feat: Add some breadcrumbs printing install path

---

src-vue/src/plugins/modules/pull_requests.ts

So as to not destroy it while user is still reading it. Changed from the default `4.5s` to `7s`.
1 line change 👀

feat: Increase time mods PR install notification is shown

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/github/pull_requests.rs

Avoids any folder write permission issues by writing into memory and/or temp dir in Titanfall2 folder.
This started out as a small bug fix PR but uncovered a bunch of issues that prompted me to refactor most of the code entirely.
TODO:
Closes #212

refactor: Fix PR downloads permission issue

---

src-tauri/Cargo.toml

Running `cargo add SOME_CRATE` formats the config file this way so might as well fix the formatting now.

chore: Format Cargo.toml

---

src-tauri/src/lib.rs

We cannot install to `C:\Program Files\EA Games\Titanfall2` cause Windows™
As such if install fails we check for that path and show according error message.
I would kinda also wanna add a link to wiki but AFAIK links won't render clickable so it's not really super helpful...
Closes #171

fix: Add error handling if default EA App path

---

src-tauri/src/github/pull_requests.rs
src-tauri/src/main.rs
src-vue/src/components/PullRequestsSelector.vue
src-vue/src/plugins/modules/pull_requests.ts

Adds buttons to just download PR instead of installing them.
In both cases (Launcher and Mods) the button simply opens the download link in the user's default browser.
Idea for feature was conceived in discussion with @EladNLG where they mentioned that grabbing launcher download link is cumbersome to do.
Rendered:
Closes #201

Add buttons to download PRs

---

src-tauri/src/lib.rs
src-tauri/src/platform_specific/linux.rs

Removes 3 errors/warnings found by running `cargo clippy`. This is basically just code refactoring.
Tested to still work as expected on Ubuntu 22.04

fix: Address clippy errors in glibc parsing code

---

src-tauri/src/lib.rs
src-tauri/src/platform_specific/windows.rs

As pointed out by `cargo clippy`

fix: Remove unnecessary `.to_string()`

---

src-tauri/src/platform_specific/windows.rs

We no longer run a powershell command to get it. This just updates a comment. No change to actual code.

fix: Update comment regarding Origin install

---

src-tauri/src/github/pull_requests.rs
src-tauri/src/github/release_notes.rs
src-tauri/src/lib.rs
src-tauri/src/main.rs
src-tauri/src/mod_management/mod.rs
src-tauri/src/platform_specific/windows.rs
src-tauri/src/thunderstore/mod.rs

Replace more `println!()` with calls to `log::info`, `log::warn`, etc
Continuation of
- #219
- #223

refactor: Replace all `println!()` with log statements

---

src-tauri/src/github/pull_requests.rs
src-tauri/src/main.rs
src-tauri/src/mod_management/mod.rs

fix: Remove redundant string conversions

---

docs/DEVELOPMENT.md
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-vue/package-lock.json
src-vue/package.json
src-vue/src/plugins/store.ts
src-vue/src/views/SettingsView.vue

As discussed in #233 saving persistent store was broken some time ago. Calling `save` explicitly  seems to resolve it.
For good measure, also bumped plugin-store version and updated pulled dependency as [described in their README](https://github.com/tauri-apps/plugins-workspace/tree/dev/plugins/store).
- Closes #233 
- Unblocks #182

fix: Address regression around persistent store

---

.github/workflows/release.yml

Instead of creating a release and then having CI build the files, have CI build files on tag and then upload them to draft release.
Previously when making a release, this release wouldn't have any files ready until build finished (~30min). During this time the download link on the main README would be broken for example.
This PR changes it to upload files to a release draft and then that release draft can be turned into an actual release, meaning that now there's no time where a GitHub release has no files attached.
This could also be extended in the future to auto-generate release notes like how we do currently from within FligthCore dev tools.
Tested successful run in test repo here: 
https://github.com/GeckoEidechse/Temp-FlightCore/actions/runs/4598431296
and resulting draft (only I …

build: Generate release draft on tag

---

.github/workflows/push-test.yml
.github/workflows/release.yml

Use `npm clean-install` instead of `npm install`. `npm clean-install` is recommended over `npm install` for CI pipelines.
https://docs.npmjs.com/cli/v9/commands/npm-ci

build: Use `npm clean-install`

---

src-vue/src/plugins/store.ts

Saves dev mode state in persistent store, so it's automatically enabled on app launch if it was previously enabled.
Closes #214.

feat: Persist dev mode

---

src-tauri/src/mod_management/mod.rs

Fixes a regression introduced in #244 that prevented any Thunderstore mods from being uninstalled
Closes #269

fix: Fix incorrect is_empty check

---

src-vue/src/i18n/lang/de.json
src-vue/src/i18n/lang/en.json
src-vue/src/i18n/lang/fr.json
src-vue/src/views/RepairView.vue

Add missing repair view localization entries (I didn't complete German entries though, only English and French).
Closes #260.

fix: Repair view add missing i18n

---

.github/workflows/push-test.yml

Only upload platform relevant artifacts as opposed to attempt uploading artifacts not relevant to platform
Main reason of doing this is to remove the warning of "missing artifacts" caused by e.g. Windows runner looking for Linux artifacts as well next to Windows artifacts.
The warning message in question shown after CI run:

build: Only upload platform relevant artifacts

---

src-vue/src/views/ChangelogView.vue

Updates the regex so it matches both old and new release notes formats used to link to Northstar GitHub PRs.
Here's a testing screenshot with regex101 (it shows that new regex matches both formats):
Closes #194.

fix: Update regex to match new release notes format

---

.github/workflows/push-test.yml

Additionally uploading binaries separately allows for downloading just those files for testing which results in faster download speeds especially on bad internet.
When testing some PR for some feature, debug information generally isn't needed so being able to download the binary without debug information speeds up the process.
Also allows for linking directly to the zip with just the binary as opposed to the one also including debug information which helps when asking non-developers to test builds.

build: Additionally upload binaries separately from CI

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

This is a hotfix until upstream is updated or we replace the library entirely.

fix: Update game-scanner to avoid deprecated lib

---

src-vue/src/views/DeveloperView.vue

Moves release note generator to the bottom and mod install section also further down as these tools are used less often than others.

refactor: Reorder DevView elements

---

src-vue/src/components/PullRequestsSelector.vue

Default behavior for space character is to toggle collapse items; with this, pressing spacebar simply adds a space character to current search field.
Closes #296.

fix: Prevent space character from opening/closing PR collapse items

---

src-vue/src/i18n/lang/pl.json

Translations update from [Weblate](https://translate.harmony.tf) for [Northstar/FlightCore](https://translate.harmony.tf/projects/northstar/flightcore/).
Current translation status:

i18n: Translations update from Weblate

---

src-tauri/src/main.rs

Doc comments should be placed before the procedural macro decorating the function being documented.

refactor: Put doc comment before macro

---

README.md

Adds mention of weblate to README to tell users how they can submit translations.
Keeping as draft until weblate is fully set up.

docs: Mention weblate for translating

---

src-tauri/src/github/pull_requests.rs

This refactor allows for easier usage later when installing a launcher build based on commit sha only, e.g. for installing newest build of a branch.
Previously one had to pass an entire pull request struct which was unnecessary as only the commit sha from that struct was actually being used.

refactor: Only pass commit sha for installing launcher CI build

---

src-vue/src/views/mods/LocalModsView.vue

This way it's a bit easier to tell which Thunderstore mod a local mod is from.
This is mostly a band-aid solution to the wider spread problem of it being difficult to see which Thunderstore mod a Northstar mod came from.

feat: Show Thunderstore mod string in alt text

---

src-tauri/src/constants.rs
src-tauri/src/github/mod.rs

When auto generating changelog from commit titles, this turns `i18n` (which is what we set weblate PRs to be prefixed with) into `Translations`
So
```
i18n: Add Polish translations via Weblate (#320)
```
becomes
```
**Translations:**
- Add Polish translations via Weblate (#320)
```
For testing, one can simply generate changelog between `v1.14.1` and `v1.15.0` and look at the generated changelog.
Note that I'm well aware _i18n_ stands for _Internationalization_ but _Translations_ sounds more sensible to me in this case ^^

feat: Add category in changelog for i18n

---

src-tauri/src/lib.rs
src-tauri/src/main.rs
src-tauri/src/mod_management/mod.rs
src-tauri/src/repair_and_verify/mod.rs

Moves  `get_enabled_mods` into `main.rs`. Ultimately it should land in a submodule but moving it there directly while `lib.rs` still exists causes some weird import/export issues that I don't fully understand yet.
Part of #329

refactor: Move `get_enabled_mods` to `main.rs`

---

src-tauri/src/lib.rs
src-tauri/src/main.rs

Moves  `convert_release_candidate_number` into `main.rs`. Ultimately it should land in a submodule but moving it there directly while `lib.rs` still exists causes some weird import/export issues that I don't fully understand yet.
Part of #329

refactor: Move `convert_release_candidate_number` to `main.rs`

---

src-tauri/src/github/pull_requests.rs
src-tauri/src/lib.rs
src-tauri/src/main.rs

Moves  `check_is_valid_game_path` into `main.rs`. Ultimately it should land in a submodule but moving it there directly while `lib.rs` still exists causes some weird import/export issues that I don't fully understand yet.
Part of #329

refactor: Move `check_is_valid_game_path` to `main.rs`

---

src-vue/src/components/LanguageSelector.vue
src-vue/src/components/ModsMenu.vue
src-vue/src/components/PlayButton.vue
src-vue/src/components/PullRequestsSelector.vue
src-vue/src/components/ThunderstoreModCard.vue
src-vue/src/views/ChangelogView.vue
src-vue/src/views/DeveloperView.vue
src-vue/src/views/PlayView.vue
src-vue/src/views/RepairView.vue
src-vue/src/views/SettingsView.vue
src-vue/src/views/mods/LocalModsView.vue
src-vue/src/views/mods/ThunderstoreModsView.vue

This is some partial autoformatting based on the style vscode autoformat suggests.
Note that it's partial in the sense that I manually reverted some of the autoformatted code back to the original state.
In particular, autoformat quite enjoyed turning
```vue
<el-option
v-for="item in ns_release_tags"
:key="item.value"
:label="item.label"
:value="item"
/>
```
into
```vue
<el-option v-for="item in ns_release_tags" :key="item.value" :label="item.label" :value="item" />
```
which is actually harder to read IMO.
So we probably wanna figure out a way to get autoformat to run in a way that looks good to us.
Also `App.vue` uses 2 space indentation instead of 4 which the rest uses so we probably wanna figure out a way to fix that as well ^^"

style: Partially autoformat Vue source files

---

src-vue/src/plugins/modules/pull_requests.ts

Function signature changed in #313 but frontend was never updated.
To test, simply try using the _Download_ button on a Northstar launcher pull request without/with this PR.
Closes #343

fix: Pass correct argument to `get_launcher_download_link`

---

src-tauri/src/main.rs
src-tauri/src/util.rs

Moves `force_panic` and `is_debug_mode` to `utility.rs` to cleanup `main.rs`.
For testing:
- `force_panic`: simply do a force panic via DevView. FlightCore should crash as expected
- `is_debug_mode`: Debug build should show stripes on top bar while non-debug should not show them

refactor: Move some functions to utility module

---

src-tauri/src/github/release_notes.rs

We usually shouldn't hit this cause GitHub shouldn't server broken JSON and if connection failed we should error out earlier yet this was logged on Sentry.
https://northstar-kv.sentry.io/issues/4175180734/

refactor: Handle error if JSON not well-formatted for release notes

---

src-tauri/src/main.rs
src-tauri/src/util.rs

To clean up `main.rs`
For testing simply launch FlightCore and see if it can fetch playercount.
Part of #351

refactor: Move server browser fetch to util module

---

src-vue/src/components/LocalModCard.vue
src-vue/src/views/mods/LocalModsView.vue

This is in preparation of overhauling the local mods interface.
Basically just moves some stuff from `LocalModsView.vue` to `LocalModCard.vue`.

refactor: Move LocalModCard into own Vue component

---

src-tauri/src/northstar/install.rs

Handle case  instead of panicking when failing to connect to Thunderstore while trying to install Northstar.
Resolves https://northstar-kv.sentry.io/issues/4188330874/
Part of #33

fix: Handle case when failing to connect to TS while trying to install NS

---

src-tauri/src/main.rs
src-tauri/src/northstar/mod.rs
src-tauri/src/util.rs
src-vue/src/i18n/lang/de.json
src-vue/src/i18n/lang/en.json
src-vue/src/i18n/lang/fr.json
src-vue/src/i18n/lang/pl.json
src-vue/src/i18n/lang/ru.json
src-vue/src/plugins/store.ts
src-vue/src/views/PlayView.vue

With EA App replacing Origin we should update our error messages and relevant function names accordingly.
Closes #361 
TODO:

refactor: Change error messages and function names to EA App

---

src-tauri/src/mod_management/mod.rs

Return error on TS package index fetch fail instead of panicking
Resolves:
https://northstar-kv.sentry.io/issues/4194989478/

fix: Return error on TS package index fetch fail

---

src-vue/src/components/LanguageSelector.vue
src-vue/src/main.ts

Adds _Italian_ into the language dropdown menu in settings.
Requires #366

i18n: Enable Italian translations

---

src-tauri/src/mod_management/mod.rs

Logs the folders accessed when trying to discover mods.
Reason being that we have some weird crash based on directory that I haven't fully figured out so this should help in discovering it.

feat: Log folder names when indexing mods

---

src-tauri/src/github/pull_requests.rs
src-tauri/src/github/release_notes.rs

Remove some unwraps for fetching GitHub API to prevent thread from panicking on no internet
Addresses: https://northstar-kv.sentry.io/share/issue/3ebc5a2c95234439863ad80a5001f203/ (finally found out how to publicly share crash reports)
Part of #33

fix: Remove some unwraps for fetching GitHub API

---

src-tauri/src/main.rs

Removes an `unwrap` that would cause  a thread crash on update checking without internet.
Addresses https://northstar-kv.sentry.io/share/issue/086424ab97b541acad0a7d0d5c9b65b2/
Part of #33

fix: Remove unwrap from Northstar update check

---

src-vue/src/components/ThunderstoreModCard.vue
src-vue/src/i18n/lang/en.json
src-vue/src/plugins/modules/search.ts
src-vue/src/views/SettingsView.vue
src-vue/src/views/mods/ThunderstoreModsView.vue

Since we don't want users to install deprecated mods, these are not displayed by default on the Thunderstore mods view.
If users like to live dangerously, they still can activate deprecated mods display via a dedicated option in the settings; deprecated mods cards will then appear with a particular style.
---
Closes #307.

fix: Don't show deprecated mods

---

src-vue/src/components/ModsMenu.vue
src-vue/src/utils/thunderstore/version.ts
src-vue/src/views/ModsView.vue
src-vue/src/views/mods/ThunderstoreModsView.vue

* A badge displays count of outdated mods
* Outdated mods are always displayed first
Closes #293.

feat: Show outdated Thunderstore mods first

---

src-vue/src/views/DeveloperView.vue

Basically just autosets the tags to the last two recent so that in most cases I can just directly click on `Compare tags` without having to manually select the first ^^

feat: Select most recent release tags after fetch

---

src-vue/src/views/mods/ThunderstoreModsView.vue

Deprecated mods are filtered out from vanilla (*i.e.* not the one used while searching) mods list.
Closes #386.

fix: Hide deprecated mods in vanilla mods list

---

src-vue/src/components/ThunderstoreModCard.vue

Mod installation notification translation would fail when invoked outside of the triggering Vue component; this addresses the issue by capturing the translation method in a context, so it's available when notification is fired up.
---
---
Closes #384.

fix: Display install messages even outside mod view

---

src-vue/src/views/mods/ThunderstoreModsView.vue

With the current logic the modview would change while its trying to scroll, resulting in the scrollbar getting messed up and the scrolling stopping in the middle of the page.
This PR:
- Uses `update:current-page` event for setting the page index
- Uses `current-change` for scrolling
(`update:current-page` is emitted before `current-change`)
- delays the `scrollTo` call by 100ms

fix: delay scrolling the Mods View to prevent it stopping prematurely

---

src-vue/src/i18n/lang/en.json
src-vue/src/views/RepairView.vue

In preparation for Northstar releasing merged Mod Settings mod.

feat: Add button to disable ModSettings mod

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/constants.rs
src-tauri/src/platform_specific/windows.rs

closes #101
Not compiled on Windows (I don't have a setup for that, so someone else needs to do it).
Error message was updated to reflect this works on Origin and the EA App (should the text be changed to only mention the EA App, since Origin is considered defunct?), though the function name was not updated.
Moved winapi and winreg dependencies into the windows only dependencies, since other systems don't make use of them.

chore: replace game_scanner usage with winreg

---

src-vue/src/views/DeveloperView.vue

In most cases after fetching tags one wants to generate release notes for the two newest. This change saves another click by just running the function directly afterwards.

feat: Run `compareTags()` directly after fetching

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/mod_management/mod.rs
src-tauri/src/northstar/install.rs

Bumps `libthermite` to newest version which should hopefully fix #406 
The library had some API changes from `0.5` to `0.6` that need to be accounted for.
Closes #406

chore: Bump libthermite to `0.6.5`

---

src-tauri/src/github/mod.rs

Toolchain updated and new clippy managed to find a previously undetected anti-pattern.

fix: Address anti-pattern found by newer clippy

---

src-tauri/src/mod_management/legacy.rs
src-tauri/src/mod_management/mod.rs

Moves some logic related to reading legacy installed mods to new file in order to clean up code before adding new logic.
Part of #415

refactor: Move code for legacy mod install reading to separate file

---

src-tauri/src/mod_management/mod.rs

Allows printing `ParsedThunderstoreModString` in the Thunderstore mod string format.

feat: Implement `to_string` for `ParsedThunderstoreModString`

---

src-tauri/src/mod_management/mod.rs

Otherwise we accept improper formatted Thunderstore mod strings like `AUTHOR-MOD-VERSION-RANDOM_STUFF`.

fix: Add regex check for parsing TS mod string

---

src-tauri/src/mod_management/legacy.rs
src-tauri/src/mod_management/mod.rs

refactor: Move code for legacy TS mod deletion to separate file

---

src-vue/src/components/LanguageSelector.vue
src-vue/src/main.ts

Adds _Simplified Chinese_ to the language dropdown menu in settings.

i18n: Enable Simplified Chinese translations

---

src-tauri/src/mod_management/mod.rs

- Depends on #417
Part of #415

feat: Add ability to delete package

---

src-tauri/src/github/release_notes.rs

Worked on PRs before the latest release was tagged causing a notification saying "Update Flightcore, you are running {newer version}. Newest ist {older version}"

feat: Compare Flightcore versions as semver

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/mod_management/legacy.rs
src-tauri/src/mod_management/mod.rs

feat: Support installing Thunderstore packages

---

src-tauri/src/mod_management/mod.rs

This is an initial implementation to prevent mods with plugins from being installed.
The goal is to get something like #267 where plugins can be installed if the user opts into installing plugins. Maybe with a warning if they wanna continue etc.

feat: Prevent mods with plugins to be installed

---

src-tauri/src/mod_management/mod.rs
src-tauri/src/mod_management/plugins.rs

Plugins in Northstar have unrestricted device access. As such we want to warn user before installing one with option to abort.
This implementation does not support localisation and the like as it uses Tauri dialogs #418 which are not translated via `vue-i18n`. 
The long term goal is to have the prompt in frontend to allow for localisation but doing it this way for now allow for rapid implementation and deployment ^^
For testing you can try to install [`cat_or_not-Furnace-1.0.0`](https://northstar.thunderstore.io/package/cat_or_not/Furnace/1.0.0)

feat: Add basic warning on plugin install

---

src-tauri/src/main.rs
src-tauri/src/util.rs
src-vue/src/views/DeveloperView.vue

At times Northstar (or rather Titanfall2 in general) locks up completely and needs to be killed.
This adds a button to kill Titanfall2.exe or NorthstarLauncher.exe to the Dev View.
Untested.

feat: Add button to forcefully terminate Northstar

---

src-tauri/src/northstar/install.rs
src-tauri/src/util.rs

This would allow preprocessing to be done ahead of time, like moving the dll into the profile or renaming the profile.
Nothing is actually done yet, because of some missing bits in Northstar.

Extract Northstar into temporary location before installing

---

src-vue/src/views/DeveloperView.vue

Adds a button to copy release notes to clip board and also auto-copies them when done generating.

feat: Copy release notes to clipboard

---

src-tauri/src/github/pull_requests.rs
src-vue/src/plugins/modules/pull_requests.ts

Passes the whole `GameInstall` object instead of individual path to functions related to PR installs.
This is done in preparation for #444

refactor: Use `GameInstall` object for PR install functions

---

src-tauri/src/repair_and_verify/mod.rs

Go over all folders during cleanup instead of early return on error.
If we early return if some folder is non-empty we will skip the remaining folders that might actually be empty.

fix: Go over all folders during cleanup

---

src-vue/src/components/ThunderstoreModCard.vue

Give thunderstore mod card images a background color to prevent alpha issues
**Before:**
**After:**
Not noticable on images with no alpha, chose lightgrey because of the lack of contrast.

fix: Give thunderstore mod card images a background color

---

src-tauri/src/constants.rs
src-tauri/src/northstar/install.rs

This is done so that with profiles we can run different versions of Northstar which would use different versions of the `Northstar.dll`

Move DLL into Profile for non default Profiles

---

src-tauri/Cargo.toml

Allow to use whatever is newest patch release.
For some reason I dropped specifying the patch version for `sentry` but still specified it for `sentry-log`. Given that the two kinda go together we should either specify patch version for both or neither. I'm tending towards the latter ^^

chore: Do not specify patch version for `sentry-log`

---

src-tauri/src/github/mod.rs

Generating release notes for FlightCore always had two trailing newlines due to the way the code is setup to expect more categories.
Had to remove them every time I made release and it got annoying.
Simply strip the remaining newlines at the end of the release notes to solve that :>

feat: Strip trailing newline from release notes

---

src-tauri/Cargo.toml

No clue how it happened but `Cargo.toml` and `Cargo.lock` do not agree on the version of `regex`.

chore: Set regex to correct version in Cargo.toml

---

src-tauri/src/main.rs
src-tauri/src/northstar/mod.rs
src-tauri/src/northstar/profile.rs
src-vue/src/i18n/lang/en.json
src-vue/src/plugins/store.ts
src-vue/src/views/SettingsView.vue

add dropdown menu for profiles

feat: Add dropdown menu for profiles

---

src-tauri/src/repair_and_verify/mod.rs

when a directory could not be read it errored out.
This PRs continues instead.

fix: Ignore missing temp directories on cleanup

---

src-tauri/Cargo.toml

Allow to use whatever is newest patch release.

chore: Do not specify patch version for `log`

---

src-tauri/src/northstar/install.rs

Remove hashes around raw string literal clippy said they are "unnecessary"
Should resolve current CI failure

fix: Remove hashes around raw string literal

---

src-vue/src/components/LanguageSelector.vue
src-vue/src/main.ts

Adds _Spanish_ to the language dropdown menu in settings.

i18n: Enable Spanish translations

---

src-tauri/src/constants.rs

So for some reason when I started out writing this file I used standard comments to annotate the constants.
Using doc comments makes more sense here as they get taken into account when generating documentations.

fix: Turn comments into doc comments

---

.github/dependabot.yml

The repo root dir also has a `package.json` which contains the necessary build tools. We wanna keep those up-to-date as well.

build: Add npm packge in root dir to bot config

---

src-tauri/src/constants.rs
src-tauri/src/northstar/mod.rs

All major proton versions can run Northstar out of the box or with minor configurations:
- Proton 8 needs a DLLOVERRIDE
- GE-Proton works like a charm with a special Northstar case
- NorthstarProton always worked

feat: Remove compatibility tool check

---

src-tauri/src/main.rs
src-tauri/src/northstar/profile.rs
src-vue/src/i18n/lang/en.json
src-vue/src/views/SettingsView.vue

This adds a button and corresponding logic to delete an existing profile
Spliced out from #444

feat: Add button to delete profile

---

src-tauri/src/main.rs

Use fully qualified path for variable instead of importing it directly

refactor: Use fully qualified path for vars and funcs

---

src-tauri/src/main.rs
src-tauri/src/northstar/install.rs

Move Northstar installation logic to module in order to clean up `main.rs`

refactor: Move NS installation logic to module

---

src-vue/src/App.vue

Spliced out from #615 
The button was removed to make space for the notification icon.
The window can still be maximised by double-clicking the top bar, dragging the window to the top of the screen, or by using keyboard shortcuts.

refactor: Remove maximize window button

---

src-tauri/src/main.rs
src-tauri/src/repair_and_verify/mod.rs

Move `clean_up_download_folder_wrapper` to `repair_and_verify` module to clean up `main.rs`

refactor: Move `clean_up_download_folder_wrapper`

---

src-tauri/src/main.rs
src-tauri/src/northstar/mod.rs
src-tauri/src/util.rs

Move `convert_release_candidate_number` to `util` module to clean up `main.rs`

refactor: Move `convert_release_candidate_number`

---

src-vue/src/App.vue
src-vue/src/components/NotificationButton.vue
src-vue/src/i18n/lang/en.json
src-vue/src/i18n/lang/fr.json
src-vue/src/plugins/modules/notifications.ts
src-vue/src/plugins/store.ts
src-vue/src/style.css
src-vue/src/utils/ui.ts

This PR introduces a notification menu, which hosts notifications fired while the app was not focused.
Notifications can be closed by the user.
Closes #400.

feat: Notification menu

---

src-tauri/src/util.rs

Address broken release-candidate number conversion for double digit patch releases
`v1.19.10-rc1` would get converted to `v1.19.11` instead of `v1.19.1001`.
Tested with #652

fix: Address broken rc number conversion

---

src-tauri/src/util.rs

Adds unit test for converting release candidate numbers.
~~Does not actually run the unit tests in CI. That's gonna be a separate PR.~~ Turns out I was already running unit tests for TypeScript file types generation lmao

test: Add unit tests for rc number conversion

---

src-tauri/src/util.rs

Non-release-candidate numbers are also put through the function and should be returned unchanged.

test: Add test for conversion of non-rc numbers

---

src-tauri/src/util.rs

They don't appear in the actual version numbers either.
```json5
{
"Name": "Northstar.Client",
"Description": "Various ui and client changes to fix bugs and add better support for mods",
"Version": "1.20.0", // <--- no leading `v`
"LoadPriority": 0,
"InitScript": "cl_northstar_client_init.nut",
"ConVars": [
// ...
]
// ...
}
```

test: Remove the leading `v` from version numbers

---

src-tauri/src/github/mod.rs

Turns `ci:` into `Continuous integration changes:`.
I added it as it's one of the suggested tags in https://www.conventionalcommits.org/en/v1.0.0/

feat: Add `ci:` as a valid tag in release note generator

---

.github/workflows/merge-conflict-auto-label.yml

Adds a GitHub Action that auto-adds a label to a PR in case there are merge conflicts.
Tested successfully via https://github.com/R2Northstar/NorthstarLauncher/pull/621

ci: Add Action to add label to PR on merge conflict

---

src-tauri/src/constants.rs

Forgot to add the new `ci` tag in previous PR

fix: Add missing release note generation section entry

---

src-vue/src/i18n/lang/en.json
src-vue/src/i18n/lang/fr.json
src-vue/src/utils/ui.ts

This PR introduces two notification-related changes (only applicable when application is not focused):
- display time of day in menu notifications;
- make app icon blink (on Windows at least) when a notification is fired.
Closes #634
Closes #702

feat: Notification improvements

---

src-tauri/src/main.rs
src-tauri/src/northstar/mod.rs
src-vue/src/plugins/store.ts

Make launching via Steam an arg passed to backend instead of a separate dedicated function.
Part of #752

refactor: Make launching via Steam an arg passed to backend

---

.github/workflows/push-test.yml
.github/workflows/release.yml

v3 uses Node 16 which is slated for deprecation by GitHub Actions

chore: Bump checkout action to v4

---

.github/workflows/push-test.yml
.github/workflows/release.yml

v3 uses Node 16 which is slated for deprecation by GitHub Actions

chore: Bump setup-node action to v4

---

.github/workflows/push-test.yml
.github/workflows/release.yml

v3 uses Node 16 which is slated for deprecation by GitHub Actions

chore: Bump upload-artifact action to v4

---

src-tauri/src/constants.rs
src-tauri/src/northstar/install.rs
src-tauri/src/northstar/mod.rs

Instead of defining our own const, let's just re-use the one recently added to [`libthermite`](https://crates.io/crates/libthermite).

refactor: Get Steam ID from libthermite

---

src-tauri/src/main.rs

Resolve clippy warning regarding too deeply nested code blocks
```
error: in a `match` scrutinee, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a `let`
--> src/main.rs:70:22
|
70  |           .setup(|app| {
|  ______________________^
71  | |             let app_handle = app.app_handle();
72  | |             tauri::async_runtime::spawn(async move {
73  | |                 loop {
...   |
115 | |             Ok(())
116 | |         })
| |_________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#blocks_in_conditions
= note: `-D clippy::blocks-in-conditions` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::blocks_in_conditions)]
```

fix: Resolve clippy warning

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-tauri/src/util.rs
src-vue/src/views/DeveloperView.vue

Adds dev tool to semi-auto-generate the release announcements I post in `#releases` on the Northstar Discord server.
The idea being that this should help me in reducing some of manual labour required to creating releases.

feat: Release announcements generator

---

src-tauri/src/github/pull_requests.rs

Use `u64` for PR number instead of `i64` as PR numbers can never be negative.
Discovered while working on #807

refactor: Use `u64` for PR number

---

src-tauri/src/constants.rs
src-tauri/src/github/pull_requests.rs

Use the [`octocrab`](https://crates.io/crates/octocrab) library for interacting with GitHub for getting the list of pull requests
Part of:
- #806

refactor: Use dedicated library for getting PR list

---

src-tauri/src/github/release_notes.rs

Instead of writing our own logic to achieve this.
Part of:
- #806

refactor: Use `octocrab` library for fetching release notes

---

src-tauri/src/github/release_notes.rs

Use [`octocrab`](https://crates.io/crates/octocrab) for fetching latest FlightCore release version number instead of using our own logic for it.
Part of
- #806

refactor: Use octocrab for fetching latest FC release version

---

src-tauri/src/github/release_notes.rs

Return actual error instead of `unwrap`ping so we don't crash the thread on connection error but instead return an error message.

fix: Return actual error instead of unwrapping

---

src-vue/src/plugins/store.ts

Shows an error message if retrieving release notes failed instead of just doing nothing.

fix: Show error message in case of failure

---

src-tauri/src/github/release_notes.rs

Improve release note formatting by putting bold inside underline
In the source, the underscores are harder to see if all the text is already underlined

style: Improve release note formatting

---

src-vue/package-lock.json

Apparently the current version has some security vuln according to npm. It doesn't affect us but bumping it won't hurt either.

chore: bump vite from 3.2.7 to 3.2.8

---

src-vue/src/views/mods/LocalModsView.vue

Initial PoC to add a button to local mod view to directly disable all mods except core ones.
This button already exists in RepairView but given how cumbersome that is to access, having a button additionally directly in the local mods view would be nice.
For context I observed a lot of cases recently on the Northstar Discord where players would have their game break by conflicting mods and staff would tell them to try to disable individual mods one-by-one. I would argue that instead having a quick way to disable all mods and then slowly re-enabling them would be a way faster method of reducing the player's issue.
This PR adds a button to achieve just that ^^

feat: Add disable all mods button to local mod view

---

src-tauri/src/main.rs
src-tauri/src/platform_specific/linux.rs
src-tauri/src/platform_specific/mod.rs
src-vue/src/views/DeveloperView.vue

With NorthstarProton changing to be GEProton based the glibc requirement is no longer needed since it targets the steam runtime

chore: Remove Linux checks

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-vue/package-lock.json
src-vue/package.json

uses the dependency declaration recommended by upstream and lets us get rid of ugly build errors

chore: Update tauri-plugin-store

---

.github/dependabot.yml

Daily feels a bit too much at this point given how many dependencies we have and how often some of them are updated. Weekly feels a bit more sane in that regard.

chore: Change dependabot PR interval to weekly

---

src-tauri/src/northstar/install.rs

`find_app` returns a complex a `Result<Option<t>>` which gives us the tristate of 
1. checked and its there
2. checked and its not there
3. something fucked up
we only caught 1 and 3

fix: Properly handle steamlocate app location tristate

---

src-tauri/src/mod_management/mod.rs

https://rust-lang.github.io/rust-clippy/master/index.html#/to_string_trait_impl

fix: Address clippy warning around direct `ToString` implementation

---

src-vue/src/App.vue

Element Plus implements the menu using lists which do not render outlines, which all other objects use to implement the focus outline.
Also the dev menu entry is not tab indexed for some reason?
Element Plus just kinda sucks.

fix: Use border when focusing menu items

---

src-vue/src/plugins/modules/search.ts
src-vue/src/views/SettingsView.vue
src-vue/src/views/mods/ThunderstoreModsView.vue

Add an option to filter out NSFW mods from Thunderstore and filter them out by default.
Found out rn that we apparently didn't do that yet, so I added the necessary logic to filter out NSFW mods by default with a switch to enable/disable the filter if desired.

feat: Filter NSFW mods by default

---

src-tauri/Cargo.lock

Bump some Rust dependencies to latest version to fix current compilation errors with latest toolchain

chore: Bump some Rust dependencies to latest version

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/github/release_notes.rs

Pick random adjective when generating release notes from a list of predefined ones

feat: Pick random adjective when generating release notes

---

src-tauri/src/constants.rs
src-tauri/src/mod_management/mod.rs

Prevent installation of Vanilla+ mod as it has special installation requirements that makes it not installable like common Northstar mods.

feat: Prevent installation of Vanilla+ mod

---

src-tauri/src/mod_management/mod.rs

We already have `anyhow` for boxing the error so we can just bubble it up
Should fix https://northstar-kv.sentry.io/share/issue/e40587c4b0cb40038b234a17e7a0bf78/

fix: Remove unnecessary unwraps

---

src-vue/src/App.vue

Usually players care more about mods than changelogs so it should be further in front.
Old:
New:
(stripes are from dev build and unrelated)

feat: Switch location of Mods and Changelog tabs

---

src-tauri/src/github/mod.rs

Sort contributors case insensitive when generating Northstar release notes
**Before:**
**After:**

fix: Sort contributors case insensitive

---

src-vue/package-lock.json

```
rollup  <2.79.2
Severity: high
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS - https://github.com/advisories/GHSA-gcx4-mw62-g8wm
fix available via `npm audit fix`
node_modules/rollup
vite  <=3.2.10
Severity: moderate
Vite's `server.fs.deny` did not deny requests for patterns with directories. - https://github.com/advisories/GHSA-8jhw-289h-jh2g
Vite DOM Clobbering gadget found in vite bundled scripts that leads to XSS - https://github.com/advisories/GHSA-64vr-g452-qvp3
Vite's `server.fs.deny` is bypassed when using `?import&raw` - https://github.com/advisories/GHSA-9cwx-2883-4wfx
fix available via `npm audit fix`
node_modules/vite
2 vulnerabilities (1 moderate, 1 high)
```

chore: Bump vulnerable npm packages

---

src-tauri/src/northstar/mod.rs

https://rust-lang.github.io/rust-clippy/master/index.html#zombie_processes
```
warning: spawned process is never `wait()`ed on
--> src/northstar/mod.rs:217:23
|
217 |           let _output = std::process::Command::new("C:\\Windows\\System32\\cmd.exe")
|  _______________________^
218 | |             .args(["/C", "start", "", &ns_exe_path, &ns_profile_arg])
219 | |             .spawn()
220 | |             .expect("failed to execute process");
| |________________________________________________^
|
= note: consider calling `.wait()`
= note: not doing so might leave behind zombie processes
= note: see https://doc.rust-lang.org/stable/std/process/struct.Child.html#warning
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#zombie_processes
= note: …
```

fix: Address clippy error regarding zombie child process

---

.github/workflows/push-test.yml

Rust toolchain updates every six weeks including clippy. With new updates clippy can cover more cases that it previously missed so with weekly CI runs we can catch these cases and fix them in a timely manner.

ci: Run CI weekly to cover Rust toolchain updates
